
import { useState, useEffect } from "react";
import "../Styles/EventPopup.css";

export default function EventAddPopup({ isOpen, onClose }){
    if (isOpen==false) return null;
    return (
        <div class="appointment-form">
            {/* initial html generated by chatgpt */}
            <button class="close-btn" onClick={handleClose}>&times;</button>

            <h2>Request Interview</h2>

            <form action={handleSubmit}>
                <label for="date">Date</label>
                <input type="date" id="date" name="date" placeholder="5-8-2026" />

                <label for="time">Start Time</label>
                <input type="time" id="time" name="time" />

                <label for="name">Interviewer's Name</label>
                <input type="text" id="name" name="name" placeholder="John Doe" />

                <label for="email">Interviewer's Email</label>
                <input type="email" id="email" name="email" placeholder="john@example.com" />

                <button type="submit" class="submit-btn">Submit</button>
            </form>
        </div>
    );
    function handleClose(){
        onClose({success: false, msg: "Event Schedule Closed."});
    }
    function handleSubmit(formData){
        let dateObj = {
            success: true,
            date: formData.get("date"),
            time: formData.get("time"),
            interviewerName: formData.get("name"),
            interviewerEmail: formData.get("email"),
        }

        // fetch post

        if (dateObj.date=="" || dateObj.time=="" || dateObj.interviewerName=="" || dateObj.interviewerEmail==""){
            dateObj.success = false;
            dateObj.msg= "Please fill out all fields.";
            onClose(dateObj);
            return;
        }
        onClose(dateObj);
    }
};