
import { useState, useEffect } from "react";
import "../Styles/EventPopup.css";

export default function EventAddPopup({ isOpen, onClose }){
    if (isOpen==false) return null;
    return (
        <div class="appointment-form">
            {/* initial html generated by chatgpt */}
            <button class="close-btn" onClick={onClose}>&times;</button>

            <h2>Request Interview</h2>

            <form>
                <label for="date">Date</label>
                <input type="date" id="date" name="date" placeholder="5-8-2026" />

                <label for="time">Start Time</label>
                <input type="time" id="time" name="time" />

                <label for="name">Interviewer's Name</label>
                <input type="text" id="name" name="name" placeholder="John Doe" />

                <label for="email">Interviewer's Email</label>
                <input type="email" id="email" name="email" placeholder="john@example.com" />

                <button type="submit" class="submit-btn" onClick={handleSubmit} >Submit</button>
            </form>
        </div>
    );
    function handleSubmit(e){
        e.preventDefault();
        alert("Submitted!");
        onClose();
    }
};